## Working with Missing Data in Pandas

In [4]:
import numpy as np
import pandas as pd

from pandas import DataFrame

In [5]:
data = {'Names': ["Steve", "John", "Richard", "Sarah", "Randy", "Micheal", "Julie"],
        "Age": [20, 22, 20, 21, 24, 23, 22], 
        "Gender": ["Male", "Male", "Male", "Female", "Male", "Male", "Female"],
        "Rank": [2, 1, 4, 5, 3, 7, 6]}

In [6]:
ranking_df = DataFrame(data)

In [7]:
ranking_df

     Names  Age  Gender  Rank
0    Steve   20    Male     2
1     John   22    Male     1
2  Richard   20    Male     4
3    Sarah   21  Female     5
4    Randy   24    Male     3
5  Micheal   23    Male     7
6    Julie   22  Female     6

In [8]:
ranking_df.iloc[2:5,1] = np.nan
ranking_df.iloc[3:6,3] = np.nan
ranking_df.iloc[3,:] = np.nan
ranking_df

     Names   Age  Gender  Rank
0    Steve  20.0    Male   2.0
1     John  22.0    Male   1.0
2  Richard   NaN    Male   4.0
3      NaN   NaN     NaN   NaN
4    Randy   NaN    Male   NaN
5  Micheal  23.0    Male   NaN
6    Julie  22.0  Female   6.0

In [12]:
ranking_df.isnull()

   Names    Age  Gender   Rank
0  False  False   False  False
1  False  False   False  False
2  False   True   False  False
3   True   True    True   True
4  False   True   False   True
5  False  False   False   True
6  False  False   False  False

In [13]:
ranking_df.notnull()

   Names    Age  Gender   Rank
0   True   True    True   True
1   True   True    True   True
2   True  False    True   True
3  False  False   False  False
4   True  False    True  False
5   True   True    True  False
6   True   True    True   True

In [23]:
rank_mask = ranking_df["Rank"].isnull()

rank_mask

0    False
1    False
2    False
3     True
4     True
5     True
6    False
Name: Rank, dtype: bool

In [24]:
ranking_df[rank_mask]

     Names   Age Gender  Rank
3      NaN   NaN    NaN   NaN
4    Randy   NaN   Male   NaN
5  Micheal  23.0   Male   NaN

In [16]:
bool_series = pd.isnull(ranking_df["Age"])

bool_series

0    False
1    False
2     True
3     True
4     True
5    False
6    False
Name: Age, dtype: bool

In [25]:
ranking_df[bool_series]

     Names  Age Gender  Rank
2  Richard  NaN   Male   4.0
3      NaN  NaN    NaN   NaN
4    Randy  NaN   Male   NaN

In [26]:
ranking_df.fillna(0)

     Names   Age  Gender  Rank
0    Steve  20.0    Male   2.0
1     John  22.0    Male   1.0
2  Richard   0.0    Male   4.0
3        0   0.0       0   0.0
4    Randy   0.0    Male   0.0
5  Micheal  23.0    Male   0.0
6    Julie  22.0  Female   6.0

In [27]:
ranking_df

     Names   Age  Gender  Rank
0    Steve  20.0    Male   2.0
1     John  22.0    Male   1.0
2  Richard   NaN    Male   4.0
3      NaN   NaN     NaN   NaN
4    Randy   NaN    Male   NaN
5  Micheal  23.0    Male   NaN
6    Julie  22.0  Female   6.0

In [29]:
ranking_df.ffill()

     Names   Age  Gender  Rank
0    Steve  20.0    Male   2.0
1     John  22.0    Male   1.0
2  Richard  22.0    Male   4.0
3  Richard  22.0    Male   4.0
4    Randy  22.0    Male   4.0
5  Micheal  23.0    Male   4.0
6    Julie  22.0  Female   6.0

In [30]:
ranking_df.bfill()

     Names   Age  Gender  Rank
0    Steve  20.0    Male   2.0
1     John  22.0    Male   1.0
2  Richard  23.0    Male   4.0
3    Randy  23.0    Male   6.0
4    Randy  23.0    Male   6.0
5  Micheal  23.0    Male   6.0
6    Julie  22.0  Female   6.0

In [9]:
ranking_df.dropna(how='all')

     Names   Age  Gender  Rank
0    Steve  20.0    Male   2.0
1     John  22.0    Male   1.0
2  Richard   NaN    Male   4.0
4    Randy   NaN    Male   NaN
5  Micheal  23.0    Male   NaN
6    Julie  22.0  Female   6.0

In [10]:
cliff_df = ranking_df.copy()
cliff_df

     Names   Age  Gender  Rank
0    Steve  20.0    Male   2.0
1     John  22.0    Male   1.0
2  Richard   NaN    Male   4.0
3      NaN   NaN     NaN   NaN
4    Randy   NaN    Male   NaN
5  Micheal  23.0    Male   NaN
6    Julie  22.0  Female   6.0

In [11]:
cliff_df.iloc[:,2] = np.nan
cliff_df

     Names   Age Gender  Rank
0    Steve  20.0    NaN   2.0
1     John  22.0    NaN   1.0
2  Richard   NaN    NaN   4.0
3      NaN   NaN    NaN   NaN
4    Randy   NaN    NaN   NaN
5  Micheal  23.0    NaN   NaN
6    Julie  22.0    NaN   6.0

In [12]:
cliff_df.dropna(how='all')

     Names   Age Gender  Rank
0    Steve  20.0    NaN   2.0
1     John  22.0    NaN   1.0
2  Richard   NaN    NaN   4.0
4    Randy   NaN    NaN   NaN
5  Micheal  23.0    NaN   NaN
6    Julie  22.0    NaN   6.0

In [13]:
cliff_df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6]

In [17]:
ranking_df.dropna(axis=0)

   Names   Age  Gender  Rank
0  Steve  20.0    Male   2.0
1   John  22.0    Male   1.0
6  Julie  22.0  Female   6.0

### Filling missing values using fillna(), replace() and interpolate()