## Data Filtering and Selection

In [ ]:
%pip install --upgrade pip 
%pip install pandas

Requirement already satisfied: pip in /usr/local/python/3.12.1/lib/python3.12/site-packages (26.0.1)
Collecting pip
  Downloading pip-26.1.1-py3-none-any.whl.metadata (4.6 kB)
Downloading pip-26.1.1-py3-none-any.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 15.6 MB/s  0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 26.0.1
    Uninstalling pip-26.0.1:
      Successfully uninstalled pip-26.0.1
Successfully installed pip-26.1.1
Note: you may need to restart the kernel to use updated packages.
Collecting pandas
  Downloading pandas-3.0.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.4.6-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 25.0 MB/s  0:00:00m0:00:010:01
Downloading numpy-2.4.6-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 50.1 MB/s  0:00:006m0:00:01
Installing collected packages: numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pandas]2m1/2 [pandas]
Successfully installed numpy-2.4.6 pandas-3.0.3
Note: you may need to restart the kernel to use updated packages.

In [2]:
import numpy as np
import pandas as pd

from pandas import DataFrame

In [27]:
numbers_df = DataFrame(np.arange(0,90,3).reshape(10,3), index=['row 1', 'row 2', 'row 3', 'row 4', 'row 5', 'row 6', 'row 7', 'row 8', 'row 9', 'row 10'], columns=['column 1', 'column 2', 'column 3'])

In [28]:
numbers_df

        column 1  column 2  column 3
row 1          0         3         6
row 2          9        12        15
row 3         18        21        24
row 4         27        30        33
row 5         36        39        42
row 6         45        48        51
row 7         54        57        60
row 8         63        66        69
row 9         72        75        78
row 10        81        84        87

In [8]:
print(numbers_df.iloc[1,0])

9

In [14]:
numbers_df.iloc[[6,7,9], [0,1,2]]

        column 1  column 2  column 3
row 7         54        57        60
row 8         63        66        69
row 10        81        84        87

#### Comparison operators (> < = <= => == !=) and Masking.

In [17]:
mask = numbers_df > 30

print(mask)

        column 1  column 2  column 3
row 1      False     False     False
row 2      False     False     False
row 3      False     False     False
row 4      False     False      True
row 5       True      True      True
row 6       True      True      True
row 7       True      True      True
row 8       True      True      True
row 9       True      True      True
row 10      True      True      True

In [18]:
mask

        column 1  column 2  column 3
row 1      False     False     False
row 2      False     False     False
row 3      False     False     False
row 4      False     False      True
row 5       True      True      True
row 6       True      True      True
row 7       True      True      True
row 8       True      True      True
row 9       True      True      True
row 10      True      True      True

In [29]:
numbers_df[numbers_df > 30]

        column 1  column 2  column 3
row 1        NaN       NaN       NaN
row 2        NaN       NaN       NaN
row 3        NaN       NaN       NaN
row 4        NaN       NaN      33.0
row 5       36.0      39.0      42.0
row 6       45.0      48.0      51.0
row 7       54.0      57.0      60.0
row 8       63.0      66.0      69.0
row 9       72.0      75.0      78.0
row 10      81.0      84.0      87.0

In [30]:
numbers_df

        column 1  column 2  column 3
row 1          0         3         6
row 2          9        12        15
row 3         18        21        24
row 4         27        30        33
row 5         36        39        42
row 6         45        48        51
row 7         54        57        60
row 8         63        66        69
row 9         72        75        78
row 10        81        84        87

In [31]:
numbers_df.iloc[6:, 1:,]

        column 2  column 3
row 7         57        60
row 8         66        69
row 9         75        78
row 10        84        87